version: '3.7'
services: 
  laravel:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: laravel
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./laravel:/var/www/html:cached
    networks:
      - laravel
  mysql:
    image: mysql:5.7.29
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    networks:
      - laravel
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - "8081:80"
    environment:
        MYSQL_ROOT_PASSWORD: root
        PMA_HOST: mysql
    networks:
      - laravel
networks:
  laravel:
